dpkg-deb -bZgzip projects/LS.Widgets/cxls1 debs
dpkg-deb -bZgzip projects/LS.Widgets/cxls2 debs
dpkg-deb -bZgzip projects/LS.Widgets/cxls3 debs
dpkg-deb -bZgzip projects/LS.Widgets/cxls4 debs
dpkg-deb -bZgzip projects/LS.Widgets/cxls5 debs
dpkg-deb -bZgzip projects/LS.Widgets/cxls6 debs
dpkg-deb -bZgzip projects/LS.Widgets/cxls7 debs
dpkg-deb -bZgzip projects/LS.Widgets/cxls8 debs
dpkg-deb -bZgzip projects/LS.Widgets/cxls9 debs
dpkg-deb -bZgzip projects/LS.Widgets/cxls10 debs
dpkg-deb -bZgzip projects/HS.Widgets/cxhs7 debs
dpkg-deb -bZgzip projects/HS.Widgets/cxhs8 debs
dpkg-deb -bZgzip projects/HS.Widgets/cxhs4 debs
